<?php
 
return [
 
  'us' => 'English',
  'id' => 'Indonesian',
  'hu' => 'Hungarian',
  'jp' => 'Japanese',
  'cz' => 'Czech',
  'de' => 'Deutsch',
  'nl' => 'Dutch',
  'es' => 'Spanish',
  'pt' => 'Portuguese',
  'fr' => 'French',
  'it' => 'Italian',
  'ru' => 'Russian',
  'tw' => 'Chinese',
 
 
  'title' => 'Pagamento',
  'connecting' => 'Connessione...',
 
  // Nav Pages
  'billing_page' => 'Compra',
  'balance_page' => 'Saldo',
  'cart_page' => 'Carrello',
  'plan_page' => 'I miei piani',
  'servers_page' => 'Server',
  'console_page' => 'Console',
  'files_page' => 'File',
  'databases_page' => 'Database',
  'shedulers_page' => 'Pianificazioni',
  'users_page' => 'Utenti',
  'backups_page' => 'Backups',
  'network_page' => 'Rete',
  'startup_page' => 'Avvio',
  'settings_page' => 'Impostazioni',
  'manage_page' => 'Gestisci',
  'account_page' => 'Account',
  'admin_page' => 'Admin',
  'out_page' => 'Log Out',
 
  // Account
  'account_balance' => 'Saldo dell\'account',
  'paypal' => 'PayPal',
  'stripe' => 'Stripe',
  'billing_information' => 'Informazioni di pagamento',
  'amount_info' => 'Inserisci quanto vuoi caricare',
  'card_holder' => 'Proprietario della carta',
  'email' => 'Email',
  'caed_number' => 'Numero di Carta',
  'cvv' => 'CVV',
  'pay_now' => 'Paga ora',
  'username' => 'Username',
  'address' => 'Indirizzo',
  'first_name' => 'Nome',
  'last_name' => 'Cognome',
  'city' => 'Città',
  'country' => 'Nazione',
  'postal_code' => 'Codice Postale',
  'update_billing_nformation' => 'Aggiorna informazioni di pagamento',
  'edit_account' => 'Modifica l\'account',
  'account_api' => 'Account API',
  'billing_balance' => 'Saldo',
  'admin_area' => 'Area Admin',
  'dark_mode' => 'Modalità scura',
  'logout' => 'Logout',
 
  // Cart
  'checkout' => 'Cassa',
  'game' => 'Gioco',
  'billed' => 'Fatture',
  'actions' => 'Azioni',
  'empty_cart' => 'Il carrello è vuoto.',
  'place_order' => 'Invia ordine',
  'plan_name' => 'Nome del Piano',
  'total_order' => 'Ordine totale: ',
  'cancel' => 'Cancella',
  'confirm' => 'Conferma',
  'confirm_place_order_info' => 'Dopo aver premuto "Conferma ordine", il tuo ordine verrà effettuato e l\'importo verrà ridotto dal saldo corrente.',
 
  // Billing
  'date_label' => 'Data',
  'price_label' => 'Prezzo',
  'view_plan' => 'Vedi i piani',
  'view_invoices' => 'Vedi le ricevute',
  'extend' => 'Estendi',
  'days_for' => 'giorni per',
  'deleted' => 'Cancellato',
  'pay' => 'Paga',
  'are_you_sure' => 'Sei sicuro?',
  'remove' => 'Rimuovi',
  'close' => 'Chiudi',
 
  // Plans
  'plans_labal' => 'Piani',
  'add_to_cart' => 'Aggiungi al carrello',
  'description' => 'Descrizione',
  'monthly' => 'Mensilmente',
  'year' => 'Anno',
  'quarterly' => 'Trimestrale',
  'unlimited' => 'Illiminato',
  'days' => 'giorni',
  'cpu' => 'CPU:',
  'ram' => 'RAM:',
  'storage' => 'Disco:',
  'backup' => 'Backup(s)',
  'database' => 'Database(s)',
  'exstra_ports' => 'Porte Extra',
 
  // Invoices
  'invoice_date' => 'Data della ricevuta:',
  'due_date' => 'Scadenza:',
  'invoice_price' => 'Prezzo:',
  'renew_plan' => 'Rinnova piano',
  'view_invoices' => 'Visualizza fatture',
  'request_cancellation' => 'Richiedi cancellazione',
  'extend_plan_info' => 'Il completamento del pagamento estenderà il tuo piano, fai clic sul pulsante "Paga" di seguito per estendere.<br> Dopo aver premuto il pulsante di pagamento, i soldi dal sando verranno rimossi. <br>',
  'remove_plan_info' => 'La richiesta di cancellazione cancellerà il server, cancellando tutti i file senza possibilità di ripristino. Se il server è attivo perderai i soldi spesi senza possibilità di restituirli!!!',
 
 
  // Success
  'plan_added_cart' => 'Aggiungi il piano al carrello',
  'server_create_success' => 'Il tuo server è stato creato con successo, vai su I miei piani per maggiori informazioni.',
  'stripe_status_url' => 'Status url: ',
  'success' => 'Successo',
 
  // Errors
  'err_remove_game' => 'Scusa. Devi prima rimuovere tutti i piani che appartengono a questo gioco.',
  'err_plan_limit' => 'Scusa. Hai raggiunto un limite. Puoi acquistare solo il seguente importo: ',
  'err_create_server' => 'Si è verificato un errore durante la creazione di un nuovo server.',
  'err_user_balance' => 'Non c\'è abbastanza saldo nel tuo account per effettuare questo acquisto.',
  'err_plan_exist' => 'Il piano è stato rimosso dal tuo carrello.',
  'err_plans_in_game' => 'Non ci sono piani per questo gioco.',
  'error' => 'Errore',

  // Domain
  'subdomain_integration' => 'Supporto Subdomain',
  'server_ip_address' => 'Indirizzo IP del Server',
  'memory' => 'Memoria',
  'plan' => 'Piano',
  'plan_subdomain' => 'Subdomain del Piano',
  'zone' => 'Zona',
  'invoices' => 'Fatture',
  'plan_error' => 'Il tuo piano non support la creazione di Subdomain',

  // Portal
  'portal_sw_mode' => 'Chiaro/Scuro',
  'portal' => 'Portale',
  'features' => 'Funzionalità',
  'games' => 'Giochi',
  'about' => 'About',
  'faqs' => 'FAQ\'s',
  'discord' => 'Discord',
  'minimize' => 'Minimizza',
  'footer_contact' => '<p>A108 Adam Street <br>New York, NY 535022<br>United States <br><br><strong>Phone:</strong> +1 5589 55488 55<br><strong>Email:</strong> info@example.com<br></p>',
  'useful_links' => 'Link utili',
  'our_services' => 'I nostri servizi',
  'about_us' => 'About Us',
  'about_us_content' => 'Write something about your host here.',
  'about_us_title' => 'Perché sceglierci?',
  'about_us_text1' => 'Offriamo dozzine di features molto utili, gestire un server non é mai stato tanto semplice.',
  'about_us_text2' => '<li><i class=\'bx bx-check-double\' ></i> User Manager</li><li><i class=\'bx bx-check-double\' ></i> Plugin Manager</li><li><i class=\'bx bx-check-double\' ></i> File Manager</li>',
  'get_started' => 'Cominciamo',
  'game_panel' => 'Game Panel',
  'game_panel_desc' => 'Il nostro intuitivo Game Panel fornisce un modo semplice per navigare attraverso il pannello. L\'area di fatturazione è direttamente integrata in quest\'ultimo. Il pannello è dotato di tutte le funzionalità di cui avrai mai bisogno e un fantastico design moderno basato su Pterodactyl.',
  'console_desc' => 'Puoi vedere gli ultimi logs della console, avviare o ibernare il server e gestire comodamente i tuoi dati.',
  'pl_installer' => 'Plugin Installer',
  'pl_installer_desc' => 'Installa oltre 65000+ Plugins con un solo click!',
  'schedules' => 'Pianificazioni',
  'schedules_desc' => 'Pianifica eventi speciali, tasks o comandi da mandare in console.',
  'happy_clients' => 'Clienti Soddisfatti',
  'active_pans' => 'Piani Attivi',
  'active_servers' => 'Servers Attivi',
  'uptime' => '% Uptime',
  'register_now' => 'Registrati Ora',
  'register_now_desc' => 'Registra il tuo account ed avvia il tuo nuovo server in pochi minuti!',
  'create_account' => 'Crea Account',
  'faq_section_title' => 'Domande poste di frequente',
  'faq_section_title_desc' => 'Di seguito una lista di domande spesso poste dai nostri clienti.',
  'features_desc' => 'Il nostro Game Panel ha una vasta varietà di features interessanti.',
  'plugins_manager' => 'Plugins Manager',
  'plugins_manager_desc' => 'Installa oltre 65000+ Plugins con un solo click! Esplora plugins nuovi e gestiscili facilmente.',
  'file_manager' => 'File Manager',
  'file_manager_desc' => 'Il nostro file manager ti consente di caricare, creare, scaricare, impostare permessi, comprimere e decomprimere file gestendoli in modo semplice',
  'backup_manager' => 'Backup Manager',
  'backup_manager_desc' => 'La nostra dashboard ti consente di eseguire backup dei tuoi file in qualsiasi momento',
  'user_manager' => 'User Manager',
  'user_manager_desc' => 'Invita amici o staffer nella tua dashboard. Puoi impostare determinate autorizzazioni per membro',
  'schedule_manager' => 'Schedule Manager',
  'schedule_manager_desc' => 'Il nostro sistema di pianificazione consente di impostare accensione/spegnimento, backup o attività a tempo',
  'database_manager' => 'Database Manager',
  'database_manager_desc' => 'Genera database MySQL, crea nuove allocazioni e molto altro',
  'game_list_desc_1' => 'Seleziona il gioco di cui vorresti vedere i Piani',
  'game_list_desc_2' => 'Non ci sono giochi disponibili.',
  'game_plans_section_text' => 'Di seguito è riportato un elenco di piani disponibili per questo gioco. Seleziona il piano più adatto a te.',
  'game_plans_section_text_empty' => 'Non ci sono giochi disponibili.',
  'team' => 'Team',
  'team_content' => 'Il nostro team è composto da sviluppatori, moderatori della community e gestori del supporto.',
  'welcome_back' => 'Lieti di rivederti,',
  'panel_dreams' => 'RHosting',
  'panel_dreams_text' => 'Hosting, up to the moon.',
  'manage_servers' => 'Gestisci i tuoi Server',
  'dashboard' => 'Dashboard',
  'easy_manage' => 'Facile gestione',
  'easy_manage_text' => 'La nostra Dashboard ti permette di gestire in modo facile e veloce i tuoi servers.',
  'portal_sw_mode_desc' => 'Scegli fra la light o dark mode.',
  'user_anagement' => 'User Management',
  'user_anagement_desc' => 'Invita amici o staffer nella tua dashboard. Puoi impostare determinate autorizzazioni per membro.',


  // Gift Card
  'gift_card' => 'Gift Card',
  'gift_card_code' => 'Codice Gift Card',
  'gift_card_not_exist' => 'La Gift Card non esiste o é scaduta',
  'gift_card_used_error' => 'Hai già usato questa gift card',
  'gift_card_used_success' => 'Il tuo saldo é stato aggiornato',
];
